# Specific redirect for /pyqs/*
[[redirects]]
  from = "/pyqs/*"
  to = "/index.html"
  status = 200
  force = true

# Catch-all redirect for the rest of the SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true